version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: prioridades-postgres
    restart: always
    environment:
      POSTGRES_USER: eusouadmin
      POSTGRES_PASSWORD: cadeiraPreta00@
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: