spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/meubanco
    username: eusouadmin
    password: cadeiraPreta00@
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
