apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ZXVzb3VhZG1pbg==       # base64 de "eusouadmin"
  POSTGRES_PASSWORD: Y2FkZWlyYVByZXRhMDBA # base64 de "cadeiraPreta00@"
  POSTGRES_DB: bWV1YmFuY28=              # base64 de "meubanco"
